// Re-export all stacks and constructs from the infra package. This allows the
// CDK app in bin/infra.ts to import stacks from a single entry point.
export * from "./queue.stack";
export * from "./storage.stack";
export * from "./users-table.stack";
export * from "./transactions-table.stack";
export * from "./lambda-alarms-construct";
export * from "./graphql-api-construct";
export * from "./graphql-api.stack";
export * from "./transaction-loader.stack";
export * from "./ssm-param.stack";
export * from "./transaction-category-loader.stack";
export * from "./transaction-category-table.stack";
export * from "./recurring-transactions-table.stack";
export * from "./budgets-table.stack";

// X‑Ray resources to enable distributed tracing. When imported from
// infra/bin/infra.ts, the XRayStack creates a sampling rule and group
// that aggregates traces generated by Lambda functions with active tracing
// turned on. See xray-stack.ts for details.
export * from "./xray-stack";
