import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import {
  CfnGroup,
  CfnSamplingRule,
} from 'aws-cdk-lib/aws-xray';

/**
 * XRayStack provisions AWS X‑Ray resources that help visualize and
 * troubleshoot the request flow across the Full Budget App. By creating a
 * sampling rule and a group, traces generated by your Lambda functions
 * (when tracing is enabled) are collected and organized in the X‑Ray
 * console. The sampling rule below captures 100 % of requests so that
 * early development and debugging sessions are comprehensive. For
 * production environments you may want to reduce the fixed rate to
 * preserve resources.
 */
export class XRayStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // Capture all requests. The rule name must be unique in the account.
    new CfnSamplingRule(this, 'FullBudgetAppXRaySamplingRule', {
      samplingRule: {
        ruleName: 'FullBudgetAppDefaultSampling',
        version: 1,
        priority: 1,
        fixedRate: 1.0,
        reservoirSize: 1,
        host: '*',
        httpMethod: '*',
        resourceArn: '*',
        serviceName: '*',
        serviceType: '*',
        urlPath: '*',
        attributes: {},
      },
    });

    // Define an X‑Ray group to logically group all traces for the application.
    new CfnGroup(this, 'FullBudgetAppXRayGroup', {
      groupName: 'FullBudgetAppGroup',
    });
  }
}
