version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   working_dir: /app/apps/api
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '4000:4000'
  #   command: pnpm dev

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   working_dir: /app/apps/worker
  #   volumes:
  #     - .:/app
  #   command: pnpm dev

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
