name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - apps/graphql-api
          - apps/txn-loaders
          - packages/auth
          - packages/client
          - packages/common
          - packages/db
          - packages/logger
          - packages/parser
          - packages/services

    defaults:
      run:
        working-directory: ${{ matrix.workspace }}

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm tsc --noEmit

      - name: Run ESLint
        run: pnpm exec eslint . --ext .ts

      - name: Check Prettier formatting
        run: pnpm exec prettier --check .
      - name: Run tests
        run: pnpm test
